// Generated by gencpp from file open_hand_controller/close_hand.msg
// DO NOT EDIT!


#ifndef OPEN_HAND_CONTROLLER_MESSAGE_CLOSE_HAND_H
#define OPEN_HAND_CONTROLLER_MESSAGE_CLOSE_HAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_hand_controller
{
template <class ContainerAllocator>
struct close_hand_
{
  typedef close_hand_<ContainerAllocator> Type;

  close_hand_()
    : FingersClose(false)
    , FingersTorque(0.0)  {
    }
  close_hand_(const ContainerAllocator& _alloc)
    : FingersClose(false)
    , FingersTorque(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _FingersClose_type;
  _FingersClose_type FingersClose;

   typedef double _FingersTorque_type;
  _FingersTorque_type FingersTorque;




  typedef boost::shared_ptr< ::open_hand_controller::close_hand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_hand_controller::close_hand_<ContainerAllocator> const> ConstPtr;

}; // struct close_hand_

typedef ::open_hand_controller::close_hand_<std::allocator<void> > close_hand;

typedef boost::shared_ptr< ::open_hand_controller::close_hand > close_handPtr;
typedef boost::shared_ptr< ::open_hand_controller::close_hand const> close_handConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_hand_controller::close_hand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_hand_controller::close_hand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace open_hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'open_hand_controller': ['/home/lukasz/workspace/src/open_hand_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::open_hand_controller::close_hand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_hand_controller::close_hand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_hand_controller::close_hand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_hand_controller::close_hand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_hand_controller::close_hand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_hand_controller::close_hand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_hand_controller::close_hand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41ffebb288e574cc8d1a1513101adeec";
  }

  static const char* value(const ::open_hand_controller::close_hand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41ffebb288e574ccULL;
  static const uint64_t static_value2 = 0x8d1a1513101adeecULL;
};

template<class ContainerAllocator>
struct DataType< ::open_hand_controller::close_hand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_hand_controller/close_hand";
  }

  static const char* value(const ::open_hand_controller::close_hand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_hand_controller::close_hand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool FingersClose\n\
float64 FingersTorque\n\
";
  }

  static const char* value(const ::open_hand_controller::close_hand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_hand_controller::close_hand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FingersClose);
      stream.next(m.FingersTorque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct close_hand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_hand_controller::close_hand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_hand_controller::close_hand_<ContainerAllocator>& v)
  {
    s << indent << "FingersClose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FingersClose);
    s << indent << "FingersTorque: ";
    Printer<double>::stream(s, indent + "  ", v.FingersTorque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_HAND_CONTROLLER_MESSAGE_CLOSE_HAND_H
