// Generated by gencpp from file open_hand_controller/contr_to_ros.msg
// DO NOT EDIT!


#ifndef OPEN_HAND_CONTROLLER_MESSAGE_CONTR_TO_ROS_H
#define OPEN_HAND_CONTROLLER_MESSAGE_CONTR_TO_ROS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_hand_controller
{
template <class ContainerAllocator>
struct contr_to_ros_
{
  typedef contr_to_ros_<ContainerAllocator> Type;

  contr_to_ros_()
    : Finger1Position(0.0)
    , Finger2Position(0.0)
    , Finger3Position(0.0)
    , FingersRotationPosition(0.0)
    , Finger1Velocity(0.0)
    , Finger2Velocity(0.0)
    , Finger3Velocity(0.0)
    , FingersRotationVelocity(0.0)
    , Finger1Torque(0.0)
    , Finger2Torque(0.0)
    , Finger3Torque(0.0)
    , FingersRotationTorque(0.0)  {
    }
  contr_to_ros_(const ContainerAllocator& _alloc)
    : Finger1Position(0.0)
    , Finger2Position(0.0)
    , Finger3Position(0.0)
    , FingersRotationPosition(0.0)
    , Finger1Velocity(0.0)
    , Finger2Velocity(0.0)
    , Finger3Velocity(0.0)
    , FingersRotationVelocity(0.0)
    , Finger1Torque(0.0)
    , Finger2Torque(0.0)
    , Finger3Torque(0.0)
    , FingersRotationTorque(0.0)  {
  (void)_alloc;
    }



   typedef double _Finger1Position_type;
  _Finger1Position_type Finger1Position;

   typedef double _Finger2Position_type;
  _Finger2Position_type Finger2Position;

   typedef double _Finger3Position_type;
  _Finger3Position_type Finger3Position;

   typedef double _FingersRotationPosition_type;
  _FingersRotationPosition_type FingersRotationPosition;

   typedef double _Finger1Velocity_type;
  _Finger1Velocity_type Finger1Velocity;

   typedef double _Finger2Velocity_type;
  _Finger2Velocity_type Finger2Velocity;

   typedef double _Finger3Velocity_type;
  _Finger3Velocity_type Finger3Velocity;

   typedef double _FingersRotationVelocity_type;
  _FingersRotationVelocity_type FingersRotationVelocity;

   typedef double _Finger1Torque_type;
  _Finger1Torque_type Finger1Torque;

   typedef double _Finger2Torque_type;
  _Finger2Torque_type Finger2Torque;

   typedef double _Finger3Torque_type;
  _Finger3Torque_type Finger3Torque;

   typedef double _FingersRotationTorque_type;
  _FingersRotationTorque_type FingersRotationTorque;




  typedef boost::shared_ptr< ::open_hand_controller::contr_to_ros_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_hand_controller::contr_to_ros_<ContainerAllocator> const> ConstPtr;

}; // struct contr_to_ros_

typedef ::open_hand_controller::contr_to_ros_<std::allocator<void> > contr_to_ros;

typedef boost::shared_ptr< ::open_hand_controller::contr_to_ros > contr_to_rosPtr;
typedef boost::shared_ptr< ::open_hand_controller::contr_to_ros const> contr_to_rosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_hand_controller::contr_to_ros_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace open_hand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'open_hand_controller': ['/home/lukasz/workspace/src/open_hand_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_hand_controller::contr_to_ros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_hand_controller::contr_to_ros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_hand_controller::contr_to_ros_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3135c65f2c721fd1f4d92d7f58d888a9";
  }

  static const char* value(const ::open_hand_controller::contr_to_ros_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3135c65f2c721fd1ULL;
  static const uint64_t static_value2 = 0xf4d92d7f58d888a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_hand_controller/contr_to_ros";
  }

  static const char* value(const ::open_hand_controller::contr_to_ros_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Finger1Position\n\
float64 Finger2Position\n\
float64 Finger3Position\n\
float64 FingersRotationPosition\n\
\n\
float64 Finger1Velocity\n\
float64 Finger2Velocity\n\
float64 Finger3Velocity\n\
float64 FingersRotationVelocity\n\
\n\
float64 Finger1Torque\n\
float64 Finger2Torque\n\
float64 Finger3Torque\n\
float64 FingersRotationTorque\n\
";
  }

  static const char* value(const ::open_hand_controller::contr_to_ros_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Finger1Position);
      stream.next(m.Finger2Position);
      stream.next(m.Finger3Position);
      stream.next(m.FingersRotationPosition);
      stream.next(m.Finger1Velocity);
      stream.next(m.Finger2Velocity);
      stream.next(m.Finger3Velocity);
      stream.next(m.FingersRotationVelocity);
      stream.next(m.Finger1Torque);
      stream.next(m.Finger2Torque);
      stream.next(m.Finger3Torque);
      stream.next(m.FingersRotationTorque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct contr_to_ros_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_hand_controller::contr_to_ros_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_hand_controller::contr_to_ros_<ContainerAllocator>& v)
  {
    s << indent << "Finger1Position: ";
    Printer<double>::stream(s, indent + "  ", v.Finger1Position);
    s << indent << "Finger2Position: ";
    Printer<double>::stream(s, indent + "  ", v.Finger2Position);
    s << indent << "Finger3Position: ";
    Printer<double>::stream(s, indent + "  ", v.Finger3Position);
    s << indent << "FingersRotationPosition: ";
    Printer<double>::stream(s, indent + "  ", v.FingersRotationPosition);
    s << indent << "Finger1Velocity: ";
    Printer<double>::stream(s, indent + "  ", v.Finger1Velocity);
    s << indent << "Finger2Velocity: ";
    Printer<double>::stream(s, indent + "  ", v.Finger2Velocity);
    s << indent << "Finger3Velocity: ";
    Printer<double>::stream(s, indent + "  ", v.Finger3Velocity);
    s << indent << "FingersRotationVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.FingersRotationVelocity);
    s << indent << "Finger1Torque: ";
    Printer<double>::stream(s, indent + "  ", v.Finger1Torque);
    s << indent << "Finger2Torque: ";
    Printer<double>::stream(s, indent + "  ", v.Finger2Torque);
    s << indent << "Finger3Torque: ";
    Printer<double>::stream(s, indent + "  ", v.Finger3Torque);
    s << indent << "FingersRotationTorque: ";
    Printer<double>::stream(s, indent + "  ", v.FingersRotationTorque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_HAND_CONTROLLER_MESSAGE_CONTR_TO_ROS_H
